apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: "{{ .Chart.Name }}"
  labels:
    app: "{{ .Chart.Name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: {{.Values.replicas}}
  template: 
    metadata: 
      labels: 
        app: "{{ .Chart.Name }}"
    spec:
      initContainers:
      - name: volume-mount-hack
        image: busybox
        command: ["sh", "-c", "chown -R 100:100 /home/ballerina/store"]
        volumeMounts:
        - name: "datadir"
          mountPath: "/home/ballerina/store"
      containers:
      - name: "{{ .Chart.Name }}"
        image: "{{.Values.image}}"
        imagePullPolicy: "IfNotPresent"
        ports:
          - containerPort: 9090
            protocol: "TCP"
          - containerPort: 9797
            protocol: "TCP"
        volumeMounts:
        - name: "datadir"
          mountPath: "/home/ballerina/store"
      volumes:
      - name: "datadir"
        persistentVolumeClaim:
          claimName: "prometheus-persistent-aggregation-pushgateway"