apiVersion: v1
kind: PersistentVolume
metadata:
  name: "{{ .Chart.Name }}"
  namespace: monitoring
  labels:
    app: "{{ .Chart.Name }}"
spec:
  storageClassName: "standard"
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  gcePersistentDisk:
    pdName: prometheus-persistent-aggregation-pushgateway
    fsType: ext4