apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Chart.Name }}"
  namespace: monitoring
  labels:
    app: "{{ .Chart.Name }}"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  selector: 
    matchLabels: 
      app: "{{ .Chart.Name }}"