apiVersion: v1
kind: Service
metadata:
  name: "{{ .Chart.Name }}"
  labels:
    app: "{{ .Chart.Name }}"
    monitor: "true"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  ports:
  - name: api
    port: 80
    protocol: TCP
    targetPort: 9090
  - name: monitoring
    port: 9797
    protocol: TCP
    targetPort: 9797
  selector:
    app: "{{ .Chart.Name }}"